images:
- gcr.io/$PROJECT_ID/ai-agent-platform:$COMMIT_SHA
- gcr.io/$PROJECT_ID/ai-agent-platform:latest
steps:
  # Build with cache optimization
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--cache-from'
      - 'gcr.io/$PROJECT_ID/ai-agent-platform:latest'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ai-agent-platform:$COMMIT_SHA'
      - '-t' 
      - 'gcr.io/$PROJECT_ID/ai-agent-platform:latest'
      - '.'
    env:
      - 'DOCKER_BUILDKIT=1'

  # Push commit-specific image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ai-agent-platform:$COMMIT_SHA']

  # Push latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ai-agent-platform:latest']

  # Deploy to Cloud Run with optimized settings
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'ai-agent-platform'
      - '--image'
      - 'gcr.io/$PROJECT_ID/ai-agent-platform:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--concurrency'
      - '80'
      - '--max-instances'
      - '100'
      - '--min-instances'
      - '0'
      - '--timeout'
      - '900'
      - '--port'
      - '8080'
      - '--set-env-vars'
      - 'ENVIRONMENT=production,LOG_LEVEL=INFO,ENABLE_PERFORMANCE_TRACKING=true'

# Build options for faster builds
options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100
  logging: CLOUD_LOGGING_ONLY

# Timeout for build process
timeout: '1200s'
