apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/execution-environment: gen2
    run.googleapis.com/ingress: all
  name: ai-agent-platform
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '100'
        autoscaling.knative.dev/minScale: '0'
        run.googleapis.com/cpu: '2'
        run.googleapis.com/cpu-throttling: 'false'
        run.googleapis.com/memory: 2Gi
        run.googleapis.com/timeout: 900s
    spec:
      containerConcurrency: 80
      containers:
      - env:
        - name: ENVIRONMENT
          value: production
        - name: LOG_LEVEL
          value: INFO
        - name: ENABLE_PERFORMANCE_TRACKING
          value: 'true'
        - name: MAX_CONCURRENT_AGENTS
          value: '100'
        image: gcr.io/PROJECT_ID/ai-agent-platform:latest
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          limits:
            cpu: '2'
            memory: 2Gi
